# Generated by Django 2.2.2 on 2019-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190624_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='title.replace(" ", "-")', max_length=250, unique_for_date='published_date'),
        ),
    ]
