# Generated by Django 2.2.2 on 2019-06-25 18:19

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190625_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_bleach.models.BleachField(),
        ),
    ]
