# Generated by Django 2.2.2 on 2019-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190629_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this post', to='blog.Category'),
        ),
    ]
